[phases.setup]
nixPkgs = ["python311", "gcc", "g++"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
